<?php

return [
    'person' => [
        'name' => 'Sahil Suthar',
        'role' => 'PHP Laravel Developer',
        'headline' => 'Laravel Developer with 2.6+ years of professional experience.',
        'experience' => '2.6+',
        'email' => 'sahilsutharrawatsar@gmail.com',
        'phone' => '+91 63776 28517',
        'phone_href' => '+916377628517',
        'location' => 'Nohar, Rajasthan, India',
        'summary' => 'I am a PHP Laravel Developer with 2.6+ years of professional experience turning business requirements into reliable web applications. My work covers backend development, REST APIs, payment gateway and third-party integrations, admin panels, MySQL optimization, bug fixing, and production maintenance.',
    ],
    'stats' => [
        ['value' => 2.6, 'suffix' => '+', 'label' => 'Years of experience'],
        ['value' => 10, 'suffix' => '+', 'label' => 'Production applications'],
        ['value' => 2, 'suffix' => '', 'label' => 'Companies'],
        ['value' => 3, 'suffix' => '', 'label' => 'Featured projects'],
    ],
    'skills' => [
        [
            'title' => 'Backend',
            'index' => '01',
            'level' => 92,
            'level_label' => 'Primary focus',
            'focus' => 'My primary development area',
            'items' => ['PHP', 'Laravel', 'CodeIgniter', 'REST API Development', 'MVC Architecture', 'Eloquent ORM', 'Middleware'],
        ],
        [
            'title' => 'Frontend',
            'index' => '02',
            'level' => 78,
            'level_label' => 'Supporting workflow',
            'focus' => 'Responsive application interfaces',
            'items' => ['HTML5', 'CSS3', 'JavaScript (ES6+)', 'jQuery', 'AJAX', 'Bootstrap 5', 'Responsive Web Design'],
        ],
        [
            'title' => 'Database',
            'index' => '03',
            'level' => 88,
            'level_label' => 'Core backend work',
            'focus' => 'Structured and efficient data',
            'items' => ['MySQL', 'SQL', 'Relational Database Design', 'Query Optimization', 'Indexing', 'Migrations'],
        ],
        [
            'title' => 'API & Security',
            'index' => '04',
            'level' => 86,
            'level_label' => 'Regular project work',
            'focus' => 'Secure system communication',
            'items' => ['RESTful APIs', 'Third-Party APIs', 'Razorpay / Stripe', 'Sanctum / Passport', 'JWT', 'RBAC', 'Input Validation'],
        ],
        [
            'title' => 'Tools & Workflow',
            'index' => '05',
            'level' => 82,
            'level_label' => 'Daily workflow',
            'focus' => 'From development to deployment',
            'items' => ['Git', 'GitHub', 'Postman', 'VS Code', 'Composer', 'npm', 'Agile / Scrum', 'SDLC', 'Deployment'],
        ],
    ],
    'experience' => [
        [
            'role' => 'PHP Laravel Developer',
            'company' => 'Veritos Infosolutions',
            'location' => 'Mohali, Punjab',
            'period' => 'May 2024 — May 2026',
            'current' => false,
            'responsibilities' => [
                'Developed Laravel backend modules and admin panels for government-sector and enterprise web applications.',
                'Created REST APIs for frontend, mobile, and external service communication.',
                'Integrated payment gateways and third-party APIs into complete business workflows.',
                'Designed and optimized MySQL queries, indexes, schemas, and Eloquent operations for better performance.',
                'Resolved application bugs, maintained existing modules, and supported production releases.',
                'Improved backend performance, validation, authentication, and role-based access across multi-user systems.',
            ],
            'stack' => ['Laravel', 'PHP', 'MySQL', 'REST APIs', 'Payment Gateways', 'Third-Party APIs', 'Admin Panels', 'Performance'],
        ],
        [
            'role' => 'Laravel Developer Trainee',
            'company' => 'D2Code Lab Pvt. Ltd.',
            'location' => 'Ellenabad, Haryana',
            'period' => 'Oct 2023 — May 2024',
            'current' => false,
            'responsibilities' => [
                'Developed backend modules with Laravel Eloquent ORM and MySQL, including CRUD operations, validation, and business logic.',
                'Built authentication, authorization, and role-based access features for live client applications.',
                'Participated in code reviews, debugging sessions, and production deployments alongside senior developers.',
            ],
            'stack' => ['Laravel', 'PHP', 'MySQL', 'Eloquent ORM', 'Authentication', 'Git'],
        ],
    ],
    'projects' => [
        [
            'name' => 'BCMR Portal',
            'type' => 'Government-sector citizen portal',
            'url' => 'https://bcmr.net.in/',
            'description' => 'A citizen-facing portal with registration, workflow management, and document tracking modules designed for a large public user base.',
            'challenge' => 'Coordinate secure, multi-role public workflows while keeping status and document movement easy to follow.',
            'solution' => 'Implemented role-aware authentication, secure form handling, structured workflow modules, and asynchronous status updates.',
            'metrics' => [
                ['value' => 'Multi-role', 'label' => 'Access model'],
                ['value' => 'Live', 'label' => 'Project status'],
                ['value' => 'Public', 'label' => 'User platform'],
            ],
            'features' => ['Citizen registration', 'Workflow management', 'Document tracking', 'Multi-role access', 'Real-time status updates'],
            'stack' => ['Laravel', 'PHP', 'MySQL', 'AJAX', 'jQuery'],
            'tone' => 'cyan',
        ],
        [
            'name' => 'Haryana Medical Council',
            'type' => 'Medical administration platform',
            'url' => 'https://haryanamedicalcouncil.org/',
            'description' => 'Online administration modules supporting medical license management and public service requests.',
            'challenge' => 'Handle high-volume administrative data and external service requests with dependable response times.',
            'solution' => 'Integrated REST APIs and optimized database queries for efficient, maintainable data operations.',
            'metrics' => [
                ['value' => 'REST', 'label' => 'Integration layer'],
                ['value' => 'Live', 'label' => 'Project status'],
                ['value' => 'MySQL', 'label' => 'Data layer'],
            ],
            'features' => ['License management', 'Public service requests', 'External API integration', 'High-volume data handling'],
            'stack' => ['Laravel', 'PHP', 'MySQL', 'REST API'],
            'tone' => 'violet',
        ],
        [
            'name' => 'Elior Booking System',
            'type' => 'Booking & reservation system',
            'url' => 'https://eliorbooking.com/',
            'description' => 'A booking and reservation platform with availability tracking and automated confirmation workflows.',
            'challenge' => 'Keep reservation availability and confirmation states synchronized through a clear booking journey.',
            'solution' => 'Designed focused booking modules that connect availability tracking with automated confirmations.',
            'metrics' => [
                ['value' => 'Booking', 'label' => 'Core workflow'],
                ['value' => 'Live', 'label' => 'Project status'],
                ['value' => 'Automated', 'label' => 'Confirmations'],
            ],
            'features' => ['Booking management', 'Reservation workflow', 'Availability tracking', 'Automated confirmations'],
            'stack' => ['Laravel', 'PHP', 'MySQL'],
            'tone' => 'green',
        ],
    ],
    'services' => [
        ['number' => '01', 'title' => 'Laravel Development', 'copy' => 'Maintainable, scalable Laravel applications shaped around real business workflows.'],
        ['number' => '02', 'title' => 'REST API Development', 'copy' => 'Secure APIs for web, mobile, and third-party integrations with clean data exchange.'],
        ['number' => '03', 'title' => 'Payment Integration', 'copy' => 'Razorpay and Stripe workflows with secure transaction handling and automation.'],
        ['number' => '04', 'title' => 'Database Design', 'copy' => 'Relational schemas, indexing, migrations, and query optimization for dependable performance.'],
        ['number' => '05', 'title' => 'Admin Systems', 'copy' => 'Role-aware dashboards, authentication, approvals, and operational management tools.'],
        ['number' => '06', 'title' => 'Application Support', 'copy' => 'Debugging, testing, deployment, maintenance, and production support for live systems.'],
    ],
    'education' => [
        ['course' => 'Bachelor of Computer Applications (BCA)', 'school' => 'Open/Distance University', 'location' => 'India', 'period' => '2025 — Present'],
        ['course' => 'Diploma in Computer Information & System Management', 'school' => 'Polytechnic Institute', 'location' => 'India', 'period' => '2023 — 2024'],
    ],
];
